spring:
  application:
    name: config-client
  cloud:
    config:
      #profile: dev
      uri: http://127.0.0.1:8091
  profiles:
    active: dev

  rabbitmq:    #本地环境不需要配置mq
    host: localhost
    port: 5672
    username: guest
    password: guest


