server:
  port: 8085
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true #检查模板是否存在再呈现
    mode: LEGACYHTML5 #关闭严格模式
  rabbitmq:
    host: localhost
    username: xue
    password: 123456
    virtual-host: /mall
