server:
  port: 8081
spring:  
  rabbitmq:
    host: localhost
    username: xue
    password: 123456
    virtual-host: /mall
    template:
      exchange: mall.item.exchange #若代码中不写exchange名称则使用此名称
    publisher-confirms: true #生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试
mybatis:
  type-aliases-package: com.mall.item.pojo
