server:
  port: 8083
spring:  
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.0.112:9300,192.168.31.205:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.31.205，192.168.0.112
    port: 5672
    username: xue
    password: 123456
    virtual-host: /mall
