server:
  port: 8086
spring:  
  rabbitmq:
    host: localhost
    username: xue
    password: 123456
    virtual-host: /mall
  redis:
    host: 192.168.31.205
    database: 1  
        
mybatis:
  type-aliases-package: com.mall.user.pojo
